website/models.py
website/templates/website/indproject.html
website/views.py

Addresses https://github.com/jonfroehlich/makeabilitylabwebsite/issues/270

Remove code redundancy in individual project members listing

---

website/admin.py
website/models.py
website/static/website/css/talks.css
website/static/website/css/video.css
website/static/website/js/backtop.js
website/static/website/js/filterBar.js
website/static/website/js/talks.js
website/static/website/js/videos.js
website/templates/website/base.html
website/templates/website/index.html
website/templates/website/publications.html
website/templates/website/talks.html
website/templates/website/videos.html
website/urls.py
website/views.py

Addresses https://github.com/jonfroehlich/makeabilitylabwebsite/issues/243

Adds video gallery

---

website/templates/website/index.html

Fixes https://github.com/jonfroehlich/makeabilitylabwebsite/issues/317 and https://github.com/jonfroehlich/makeabilitylabwebsite/issues/316

Fixes https://github.com/jonfroehlich/makeabilitylabwebsite/issues/317 and https://github.com/jonfroehlich/makeabilitylabwebsite/issues/316

---

makeabilitylabwebsite/command
requirements.txt

this branch is building correctly on -test

Fixed #338 -- formatting and a typo to fix docker builds

---

.gitignore
makeabilitylabwebsite/command

This places the static asset collection outside the docker container so it can be picked up by the front-end proxy.

Fixes #337

---

website/models.py

Changed admin display from Co advisor to Co-advisor

---

website/models.py

Current member status for future interns no longer displays active

---

website/static/website/js/videos.js

Default sorting of videos is reverse chronological

---

README.md

Changes:
* Added table of contents to the README for large headers)
* Added contributing section
I think this still needs revision (it's still not incredibly thorough). Making this pull request for now so that it's easier to review.

Resolves #385: Add contributing guide section to README

---

website/models.py

Fixes #403 
Before:
After:
Default school changed from University of Maryland to University of Washington

Resolves #403: updates default school

---

auto-deploy/index.php

This should fix the root cause of the site not updating issue.

Fixes #432 -- branch detection in autodeploy script

---

website/templates/website/base.html
website/test_cases/test_images.py

Resolves issue with PR #424 being based off of another branch.

Fix links footer

---

website/models.py
website/templates/website/people.html
website/templatetags/ml_tags.py
website/views.py

Added much simpler template code for iterating through current members. If this works well, will adopt same approach for alumni and collaborators and simplify views.py as well.

Revising people layout code

---

website/templates/website/index.html

Fixes bugs with the landing page. Now this branch should work with the newest version of master. Had to make a new branch because the old one had problems with Django and other dependencies. Link to old, closed pull request is here: #454.

fixes the landing page (#448, #447, #441), works with newest version of master

---

website/static/website/js/isotope/isotope-filterBar.js
website/static/website/js/isotope/isotope-init.js
website/templates/website/people.html

made filter not change: https://www.youtube.com/watch?v=wqneDskqoDA&feature=youtu.be
(ignore the part where the "all" is in front and not bolded)
moved all to the end and bolded it by default:

fixes #496 and #494, made all bold, moved all to end, made filter bolding stay

---

website/templates/website/index.html
website/templates/website/projects.html

Before (Project still appearing even without publications): https://cl.ly/2j3l1w2n3l2z
After (Hiding projects with no publications): https://cl.ly/0L281Z3Q120p

Hide Projects with no publications Addresses Issue #440

---

website/static/website/js/isotope/isotope-filterBar.js
website/static/website/js/isotope/isotope-filtering.js
website/static/website/js/isotope/isotope-init.js

fixes #499. Console logs are commented out.

commented out console logs

---

website/static/website/js/publications.js
website/templates/website/publications.html

Added the DOI function by linking the official url to the [doi]. 
https://cl.ly/420F08432y2v

Added DOI functionality

---

website/templates/website/index.html
website/templates/website/talks.html

Talk pdf mobile

---

website/models.py

Addresses Issue #393 
Now, the position model will throw an error if the start date begins after the end date. This adds another layer to the validation of model data.
[![Image from Gyazo](https://i.gyazo.com/fe5f7c552da4229e1344b9629b4b6f11.png)](https://gyazo.com/fe5f7c552da4229e1344b9629b4b6f11)

custom validation for position times

---

website/admin.py
website/admin_list_filters.py
website/models.py

Updated person filter for admin interface

---

website/models.py

Panel is now included as an option for the publication venue choices.

Added Panel as option to Publication Venue

---

website/static/website/js/fixedSideBar.js
website/static/website/js/isotope/isotope-filterBar.js
website/static/website/js/isotope/isotope-header-creator.js
website/static/website/js/isotope/isotope-sorting.js
website/static/website/js/publications.js
website/static/website/js/talks.js
website/templates/website/projects.html
website/templates/website/videos.html

fixes #572, fixes #573, fixes #568.
the sidebar would jump significantly on smaller screens: https://www.youtube.com/watch?v=PwHXdOKg3vU
and projects with no header are placed at the top under a blank header:
now the sidebar jump glitch is fixed: https://youtu.be/LTS1Iz9ss94
and we have an 'other' category: 
and the 'other' category is at the bottom of the list:
videos are now sorted by most recent to least recent, and projects are sorted by most recent paper.

Fixes a bunch of problems with isotope implementations

---

requirements.txt

Ugh, another security vulnerability in django detected--upgrading to 2.1.2

Ugh, another security vulnerability in django detected

---

website/templates/website/talks.html
website/views.py

Drastically changed talks.html--stripped out all javascript, including the filterbar and groupby functionality and now just using the talks snippet. I do want to add filtering and groupby back in once I figure out isotope. Good enough for now?

Update talks page to use snippets

---

website/static/website/css/base.css
website/templates/website/base.html

fixed mobile footer (#571) + some css cleanup for footer.

Mobile footer

---

website/static/website/css/project.css
website/templates/snippets/display_talk_snippet.html

fixes left alignment issue with recent video and talks in the project.html page

---

website/static/website/css/member.css
website/templates/snippets/display_project_snippet.html

fixes the space between project thumbnail and project label on member page

---

website/static/website/css/index.css

adds 20px of whitespace between project rows

---

website/static/website/css/people.css

fixes left alignment on people page

---

website/static/website/css/faq.css

fixes left alignment of sidebar menu

---

website/templates/website/faq.html

Updates FAQ sidebar to match content

---

website/static/website/css/news-listing.css

#714 
I don't have enough listings on my local server to test this, but I'm 95% sure this works.

fixes the weird font at the news page index widget

---

website/static/website/js/citationPopover.js
website/templates/website/publications.html

does not show 'none' if there is no middle name for a person in citations and bibtex

---

website/static/website/js/faq.js

allows side panel in faq page to collapse when click on the topic again

---

website/static/website/css/faq.css
website/templates/website/faq.html

adds mouseover permalinks to each question in faq

---

website/static/website/css/base.css
website/static/website/css/index.css
website/static/website/css/member.css

adds vertical spacing to project listing on both home and project page

---

website/static/website/js/faq.js
website/templates/website/faq.html

Add high school section to FAQ

---

website/templates/website/faq.html

removes punctuation from FAQ permalinks

---

website/static/website/css/faq.css
website/templates/website/faq.html

#777 
Quote font size is reduced to 14px to match other body text. 
I also renamed two classes to make more specific. I didn't like how confusing the selectors were.

Reduced quote font size

---

website/templates/snippets/display_project_gallery_lightbox.html

Edited the django code that affects the image src, should work but will be a poor quality image. I'm also going to push right away to test on the makeability test website.

Lightbox image bug temporary fix

---

website/models.py
website/static/website/css/base.css
website/static/website/js/lightbox.js
website/templates/snippets/display_project_gallery_lightbox.html

#692 
Adds a second cropping option for high quality photos used in lightbox in the admin interface, fixes scrolling bug.

Lightbox bug fixes

---

website/static/website/css/bignews.css
website/templates/website/news.html

fixes news article left side cut off

---

website/static/website/css/news-listing.css
website/templates/website/news-listing.html

makes news listing title and image clickable

---

website/views.py

Reverts jonfroehlich/makeabilitylabwebsite#790
Going to test if this PR changes the 503 error on test server

Revert "News listing banners bug fix"

---

website/models.py
website/static/website/css/base.css
website/static/website/js/lightbox.js
website/templates/snippets/display_project_gallery_lightbox.html

Reverts jonfroehlich/makeabilitylabwebsite#787
I'm reverting this PR because it edits the models.py file. I want to push a stable version of the test site to the production site.

Revert "Lightbox bug fixes"

---

website/static/website/css/bignews.css
website/static/website/css/news.css
website/templates/website/news.html

We just received another 503 error. I believe this is the PR that cause it. I'm going to revert to see if this fixes it.

Revert "Fixes left margin alignment on news article page"

---

requirements.txt
website/templates/snippets/display_news_blurb_sidebar_snippet.html
website/templates/snippets/display_people_header_snippet.html
website/templates/snippets/display_people_snippet.html
website/templates/snippets/display_person_snippet.html
website/templates/snippets/display_project_gallery_lightbox.html
website/templates/snippets/display_project_snippet.html
website/templates/snippets/display_pub_snippet.html
website/templates/snippets/display_short_carousel_snippet.html
website/templates/snippets/display_talk_snippet.html
website/templates/snippets/display_video_snippet.html
website/templates/website/base.html
website/templates/website/faq.html
website/templates/website/index.html
website/templates/website/member.html
website/templates/website/news-listing.html
website/templates/website/news.html
website/templates/website/people.html
website/templates/website/project.html
website/templates/website/projects.html
website/templates/website/publications.html
website/templates/website/talks.html
website/templates/website/videos.html

Upgrading to Django 3.2.10, which addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/838

Django upgrade 3.2.x

---

docker-compose-prod.yml
docker-compose-test.yml
docker-compose.yml
rebuildanddeploy.sh

An example of how to do this with environment specific yml files.

breaking out docker-compose files for different env, modifying script

---

website/models/position.py
website/static/website/css/people.css
website/static/website/css/publications.css
website/templates/snippets/display_pub_snippet.html
website/templates/website/people.html
website/utils/ml_utils.py
website/views/member.py
website/views/people.py

Adds easter egg, past members, and white navbar (addressing https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1054)
**Before**
**After**

Adding past members to people page

---

website/static/website/css/top-navbar.css
website/static/website/js/top-navbar.js
website/templates/website/base.html

Drastically simplified our navbar css and now support light and dark themes (to make it easier to have a white navbar at top vs. dark)

Updating nav bar to use vars

---

makeabilitylab/settings.py
website/models/project.py
website/models/project_umbrella.py
website/static/website/css/base.css
website/static/website/css/news-listing.css
website/static/website/css/project-listing.css
website/templates/snippets/display_project_snippet.html
website/templates/website/base.html
website/templates/website/index.html
website/templates/website/news-listing.html
website/templates/website/projects.html
website/views/projects.py

Updated project listing to:
* Use CSS grid rather than bootstrap
* Optimize the backend queries (which are now done in Django ORM (aka SQL layer) vs. in Python)
* Add filter

Redesigning project listing page

---

docker-entrypoint.sh
website/management/commands/rename_person_images.py
website/models/person.py
website/templates/website/people.html
website/utils/fileutils.py
website/views/people.py

Addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1052
- Renames people photos on upload to firstname_lastname.jpg
- Also does the same for their easter egg image
- Also added in a command rename_person_images.py that retroactively fixes old photo names on filesystem and database entries

Renames people photos on upload to firstname_lastname.jpg

---

website/admin/__init__.py
website/admin/sponsor_admin.py
website/models/sponsor.py
website/static/website/css/sponsor-listing.css
website/templates/website/index.html
website/views/index.py

Addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/300

Add sponsors to landing page

---

website/models/person.py
website/models/project.py
website/models/project_role.py
website/static/website/css/view_project_people.css
website/templates/website/people.html
website/templates/website/view_project_people.html
website/urls.py
website/views/__init__.py
website/views/view_project_people.py

Allows us to view all people involved in a project throughout time
Should be useful for generating a screenshot for our talks

adding in a new unlisted page for showing project people

---

website/admin/__init__.py
website/admin/person_admin.py
website/admin/position_admin.py
website/admin_list_filters/position_title_list_filter.py
website/models/person.py
website/models/position.py
website/models/project_role.py
website/views/people.py

- Rewrote code to use new TextChoices
- Added "Student Lead" position for Project Roles

Updated roles and positions

---

website/admin/project_admin.py
website/admin/video_admin.py
website/models/project.py
website/models/video.py
website/static/website/css/project.css
website/static/website/css/project_old.css
website/static/website/css/sponsor-listing.css
website/templates/website/project.html
website/templates/website/project_old.html
website/views/project.py
website/views/project_old.py

Redesigned the project pages to address https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1092

Redesigning project page

---

website/admin/grant_admin.py
website/admin/project_admin.py
website/models/artifact.py
website/models/project.py
website/views/project.py

Changed the primary funding association of projects from sponsors to grants

Changed the primary funding association of projects

---

docker-entrypoint.sh
website/admin/publication_admin.py
website/management/commands/remove_year_from_forum_name.py
website/models/artifact.py
website/models/publication.py
website/static/website/js/pub_admin_custom.js
website/templates/snippets/display_pub_snippet.html
website/utils/fileutils.py
website/utils/ml_utils.py
website/utils/timeutils.py

A pretty significant change to pub.forum_name that addresses a number of tickets, including https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1166 and https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1171

Forum name year fix

---

website/models/person.py
website/models/position.py
website/views/member.py

Including those documented:
- https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1170
- https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1154
- https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1150

Trying to fix a number of auto-generated bio bugs

---

website/urls.py
website/views/__init__.py
website/views/serve_pdf.py

Addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1173

New feature to load closest matching pub from pdf filename

---

website/templates/snippets/display_talk_snippet.html

Attempts to address https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1185

Fix talk speakers bug

---

website/templates/snippets/display_video_snippet.html

Attempts to address https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1187

Fix video object has no project

---

website/static/website/css/index.css
website/static/website/js/makelab-logo.js

Fixed responsiveness of dynamic logo: https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1193#issuecomment-2412100557

Center dynamic logo on small screen sizes

---

website/admin/publication_admin.py
website/admin/talk_admin.py
website/models/__init__.py
website/templates/admin/website/publication/change_form.html

Addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1200

Autopopulate talk form fields from publication admin UI

---

website/admin/publication_admin.py
website/admin/talk_admin.py
website/admin/video_admin.py
website/static/website/js/add_pub_id.js
website/templates/admin/website/publication/change_form.html
website/templates/admin/website/talk/change_form.html

The new VideoAdmin form (change_form) can be auto-filled from either an associated talk or publication
Addresses https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1203

Adds auto-fill functionality to video_admin
