makeabilitylab/makeabilitylabwebsite

- website/static/website/css/base.css
- website/templates/website/talks.html
You can add the class artifact-thumbnail-hover to any element that contains an image and it will zoom 20% on hover. I also added the artifact-overlay class which will add the dark overlay and the artifact-overlay-content class which sets the text and link color to white and positions it in the middle of the container (links appear as large buttons)
> Artifact thumbnail hover

- website/static/website/css/base.css
So the filter was stacked on top of the footer b/c the footer wasn't positioned (while the filters are). I set `position: relative` for the footer, and now it is stacked on top of the filters.
Here are before/after GIFs for the publications page.
*Before*
*After*
Resolves #286
> Footer now stacked on top of filters

- website/static/website/css/base.css
- website/templates/website/base.html
The 'Connect' links are moved to the bottom of the description of Makeabilitylab, which is next to the big logo. Arrows are added to the list of 'Links'. Swapped 'Recent News' and 'Links'. This PR addresses: https://github.com/jonfroehlich/makeabilitylabwebsite/issues/26
Before:
After:
> Redesign the footer

- makeabilitylab/settings.py
- makeabilitylabwebsite/command
- requirements.txt
debug log is now getting dumped to /cse/web/research/makelab/www/debug.log  which you should be able to get to from recycle.
If you want to stop, just  comment it out in settings.py
> adding mapped config.ini, updated requirements and a debug log

- website/static/website/js/videos.js
Addresses issue #276 
Sorting is both within the projects and between projects. (Videos with most recent projects come first, most recent videos for each project are listed first)
There were some problems with updating .js files with Docker, so I had to modify the run command to this in order to get the website to update correctly. Might be nice to look into this later? (new potential issue?)
New command:
```
docker run -p 8000:8000 -ti -v database:/code/db -v $(pwd)/media:/code/media -v $(pwd)/website/static/website:/code/website/static/website [tag]
```
> Videos sorted by Project are chronological

- website/static/website/js/videos.js
Addresses issue #275 
Videos that have been published more recently are displayed first.
I also had to run a long docker command in order to get the file to update correctly
```
docker run -p 8000:8000 -ti -v database:/code/db -v $(pwd)/media:/code/media -v $(pwd)/website/static/website:/code/website/static/website  v1
```
> Videos are ordered by date when sorted by year

- website/admin.py
- website/models.py
- website/urls.py
- website/views.py
Addresses issue #121 
Users URLs can now look like this (this is based off the Url Name field in `models.py`): 
Users can be found either through their member ID or their url name. Links to users are all currently through the Member IDs still (going to open up a separate issue for this)
The URL Name field is filled out as you're typing and defaults to a firstname-lastname format. I'm not sure how to get rid of the hyphen, so that might be something to look into since the format isn't perfect. This field can also be edited manually.
It also doesn't automatically generate for existing members.
> Made user urls friendlier so that people can be referenced by names

- website/templates/website/people.html
I believe that the issue found with the errant commas lies in fact that the active_phd passes both tests on lines 86 and 88 which causes two commas to be printed even though active_postdoc is false. I changed it so that the comma should only be printed if active_postdoc is true.
> Errant Commas addressed in People Listing

- Makefile
Fixes #416 
I forgot to add the volume mount flag for website earlier -- the `run` command should be fixed now.
> Resolves #416: Fix makefile typo

- .gitignore
Fixes #426 
This should take care of `debug.log` files too (since these are also stored in media).
> Resolves #426: Update gitignore to exclude media

- website/admin.py
Fixes #255 
Previously, keywords were added using the following interfaces:
1. Default ManyToMany
2. Default SortedManyToMany
These have been updated to use a *FilteredSelectMultiple* widget instead:
Features:
* Can select multiple keywords without having to deal with holding control/command keys
* Allows admin to add keywords either by typing text into the filter bar and hitting enter or by clicking an option. This lessens the number of clicks needed, which makes the process faster.
* Always displays available/chosen categories.
The FilteredSelectMultiple widget is being used on fields with `ManyToMany` relationships. Below is a list where this widget is being used now.
| Model | Field |
| ------ | ----- |
| News | Projects |
| Posters | Authors |
| Project Umbrella | Keywords |
| …
> Resolves #255: Updates admin interface to make adding keywords easier

- website/models.py
- website/views.py
Fixes #260, #262, #363 (?)
* Future project members no longer show up on the Projects page and future collaborators no longer show up on the person page. (The collaborators problem wasn't officially documented as an issue, but it was a related problem that I noticed while I was testing). 
* I didn't see any functions that differentiated between past/future collaborators. I added in an `is_past` to Project Roles (in Models) and `is_past_collaborator` to Position (in Models)
> Resolves #260, #262, #363: Hides future project members + collaborators

- .dockerignore
Could resolve #360 and possibly #366 if lucky?
I created a `dockerignore` file that excludes the `website/migrations` folder. If I remember correctly from my meeting with Jason a few weeks ago, the state of the `0001_initial.py` file seemed to be ahead of the actual database. I think this meant that Django thought it had already applied its migrations when it hadn't.
My hunch is that if we exclude the migrations folder, we'll be able to make sure that Django/the databases are in sync with each other. I tried it locally and it seemed to work fine (I was able to add/remove fields in `models.py` without any problems), and it didn't slow down any of the `docker build` or `docker run` steps.
> Resolve table updating issues (locally, but possibly on production too?)

- website/static/website/css/publications.css
- website/static/website/js/citationPopover.js
- website/templates/website/index.html
- website/templates/website/publications.html
New PR based on master. Resolves #345: 
citations on a screen wider than 600 px will default to the right, but display left if it becomes cut-off
citations will not display on mobile
> Citation Popover Issue

- website/management/commands/updateurls.py
- website/models.py
- website/templates/website/index.html
- website/templates/website/member.html
Hopefully resolves some of the issues that came up on production in #381 
This error kept coming up in the UW`debug.log` file: `django.core.urlresolvers.NoReverseMatch: Reverse for 'member' with arguments '('victorde souza',)' and keyword arguments '{}' not found. 2 pattern(s) tried: ['member/(?P<member_id>[-a-z]+)/$', 'member/(?P<member_id>[0-9]+)/$']`. It makes sense -- urls is not expecting a space in a person's url name!
I included an extra command to get rid of whitespaces. (Both in the `updateurls` command and the `save` command for person that fills the `url_name` column). Hopefully it works!
I also made some other miscellaneous fixes - I noticed that the landing page + one place in news was still referencing authors/speakers by ids instead of names. (This is done in the more …
> Fixes #381: Update url references

- website/templates/website/videos.html
Fixes #475.
Added a conditional check in `videos.js` to make sure that there is a publication associated with a video to list a Paper. 
Example:
Previously, it showed a Paper link that directed to `/media`, which causes a 403 error.
> Resolves #475: adds conditional check to see if video has a publication pdf

- website/templates/website/index.html
before:
after:
fixes the alignment bug for the "see all", adds in spacing between projects
> Landing page fixes

- website/templates/website/base.html
old:
new:
Done using bootstrap collumns, replaced &nsbp. Also added line-clamping for long titles.
> fixes #466

- website/templates/website/base.html
Transitions directly from this:
to this:
This kind of stacking no longer occurs:
> Fixes navbar stacking bug (#450)

- website/models.py
fixes the video title generation so that letters after the first letter are lowercase and the first letter is uppercase for each word in the title.
Fixed department generation so that highschool students aren't mapped to iSchool and so that a person who has more than one major has the correct abbreviation. For example, "computer science, school of information" maps to "CS,iSchool"
> Fixing bugs found in unit tests (fixes #392, #394, #396)

- website/templates/website/news-listing.html
Fixed all the issues listed in #467 
A typo led to all the images being displayed as the news icons, it has been corrected.
Using the `safe` template filter, html tags will now be rendered not as plain text but mark up instead.
Line clamps at 2 lines per item.
> Additional news fixes

- website/static/website/css/index.css
- website/templates/website/index.html
fixes #301, fixes #448, fixes #505
fixes makelab footer, increases content max-width to 1400px successfully,fixes talks/projects sizing, and removes the black borders.
Now looks like this on large screens:
> Fixing landing page.  Fixes #301, fixes #448, fixes #505.

- website/templates/website/index.html
fixes #522, #518, #519
This should fix the alignment and responsiveness and talks content collision. Re-added the background, but changed it from black to white. Should have the resizing behavior as well as the alignment.
looks like this:
> fixes the responsiveness and see all alignment and talks content collision

- website/templates/website/news-listing.html
Fixes the different sized images by adjusting the default news image to the size of the cropped images.
> one line fix to issue #521

- website/templates/website/base.html
- website/templates/website/index.html
fixes #500, fixes #532.
news list now aligned to the content:
news footer now has fixed spacing for each row:
date no longer wraps:
> fixing news list and footer

- website/views.py
Serializes the absolute path of the file on the server instead of a relative path beginning at media (Example: `/media/publications/Evaluating_Angular_Accuracy_of_Wristbased_Haptic_Directional_Guidance_for_Hand_Movement_nIxCCJA.pdf` will become `https://makeabilitylab.cs.washington.edu/media/publications/Evaluating_Angular_Accuracy_of_Wrist-based_Haptic_Directional_Guidance_for_Hand_Movement_nIxCCJA.pdf`)
> Quick additional REST API feature

- README.md
The readme now displays documentation for what the rest api does and how to use it.
> added previous documentation of REST api to the readme

- website/models.py
added the post_delete to the imports. 
originally I removed the post_delete from the imports because of a merge conflict.
> quick fix to add post_delete

- website/models.py
- website/static/website/js/publications.js
- website/templates/website/publications.html
The pull request addresses issue #456. 
Before, all the publications were marked as "To Appear" due to a bug in the javascript that looked for an element tagged with the class="publication-to-appear" whereas the actually class of the "To Appear" text has class="publication-to-appear-text". 
Now, the "To Appear" text will only appear if the date of the publication object is greater than the time today. As shown below, the "To Appear" text can now be controlled.
[![Image from Gyazo](https://i.gyazo.com/fce9fc8c39a72fb5c6f5967068aecfad.png)](https://gyazo.com/fce9fc8c39a72fb5c6f5967068aecfad)
> Fix to appear bug

- website/templates/website/index.html
- website/views.py
Put in an extra function to filter the projects first before displaying them on recent projects that way even when slicing in different amounts, which in this case is 8, that number will at least show up considering there are that many projects.
> Updated Filter to Recent Projects

- website/views.py
The site will now hide all projects that don't have any of the three things (a publication, an about text, or a thumbnail attached). This has been added to both the landing page and the projects page. In addition, I have put all the filtering into one method, thus the original method has been commented out.
> Fixes Issue #570

- robots.txt
Resolves issue #546. A robots.txt has been created according to [this site](http://www.robotstxt.org/robotstxt.html). The User-agent parameter is used to set which robots this section applies to (* for all) and the Disallow parameter is used to exclude certain parts of the website from being accessed (/ for all). 
The file must be added to the top most level directory because robots query the url `https://<base_url>/robots.txt`, stripping off the portion following the first single slash and appending `/robots.txt` to the result.
> Added a robots.txt for production site to allow all robots

- Dockerfile
Temporary workaround for #575. I'm not sure if this will work with our production site, but it gets rid of the `PermissionError: [Errno 13] Permission denied: '/code/static'` message locally (which is where the Django admin css is kept)
> Updates permissions to give apache access to the entire /code directory

- website/models.py
Revised the get_title function in Publications and talks to use a proper capitalization method that can be set to exclude certain words from capitalization. It will however catch if the first word is among the excluded articles and capitalize it regardless. 
Example:
a leading article -> A Leading Article
this and that -> This and That
[![Image from Gyazo](https://i.gyazo.com/8ec92b0abddf88199395dafa8f6311f4.png)](https://gyazo.com/8ec92b0abddf88199395dafa8f6311f4)
[![Image from Gyazo](https://i.gyazo.com/e80c5fed95a54cb9e93df2de92c47e53.png)](https://gyazo.com/e80c5fed95a54cb9e93df2de92c47e53)
> correct function to exclude articles from capitalization

- website/templates/snippets/display_people_snippet.html
Addresses issue #506 
Now, the department field of the position model is not required, and on the people page of the website, high school students will not display a department.
[![Image from Gyazo](https://i.gyazo.com/65a0d5799254535696048cc178dbac25.png)](https://gyazo.com/65a0d5799254535696048cc178dbac25)
> hides high school student department

- website/serializers.py
- website/urls.py
- website/views.py
Addresses issue #541 
Before the API only supported talks and publications for the importtalks and importpubs command; however, now the api will also serialize and return the JSON data for News, Projects, Videos, and Person objects.
> Added Additional API Support

- README.md
This PR addresses #420 #548 #549
The Readme now includes a sample api call to `/api/pubs?format=json` and some additional notes about the import pubs and import talks commands. Due to the automatic nature of the commands, there aren't many important things to take note of.
> added bootstrapping readme and sample api calls

- Dockerfile
- website/models.py
Resolves #603 
This pull request adds a regex expression for creating `url_name` that hopefully prevents future problems with names using non-ASCII characters.
Here's what we currently do to create url names:
* Add the first and last names together, turn everything into lowercase
* Go through each character in the url name, and check for any special characters (non a-z/A-Z characters)
* If there is a special character, check to see if we are mapping it to anything. (EX: ö gets mapped to o).
* Go through the name a final time, and remove any remaining regex characters. This is in case there are hyphenated names / names with periods in them.
Example:
| First name | Last name | Final url name |
| ----------- | --------- | -------------- |
| aileén | zeng- | aileenzeng | 
I also made a small …
> Resolves #603: Update how url names are created

- .dockerignore
- Dockerfile
Resolves #646.
My testing hasn't been super thorough since I don't have very much stuff in my media directory right now. I think it is fine to exclude `media` from the build context because we have a volume mount for `media` in our run command.
Testing instructions:
* Pull `646-shrink-docker-build-context`
* Run `make run` again. The build context should be maybe ~250MB. Visit the webpage to make sure that nothing is broken (maybe try clicking on some of the `media`.
* Try adding another publication/talk - check to see that it uploaded correctly
> Resolves #646: Shrinks Docker build context.

- website/static/website/css/member.css
- website/templates/snippets/display_project_snippet.html
- website/templates/website/member.html
> fixes the bug that shifted recent projects to the right on a member page

- website/templates/website/project.html
fixes #629 
Sponsors that do not have urls, will not be hyperlinked. Sponsors that are hyperlinked will open in a new tab.
> Sponsor Hyperlink Error

- website/templates/website/project.html
fixes #693 
There was a bold tag in surrounding the text in the h3 tag. It affected both recent videos and talks.
Should be good now.
> fixes recent video and talks headers in project pages to match other headings

- website/templates/snippets/display_short_carousel_snippet.html
fixes #685 
I just switched 'page_title' to 'news.title' in the if statement.
This worked as every page(besides the news.html) grabs the overlay title from the url.
May want to look into a better solution down the road.
> Fixes individual news article title

- website/static/website/js/fixedSideBar.js
#631 
I took out three lines of code that were causing the bug. I think what they were trying to do was prevent the filter bar from scrolling under the footer. However, in the Makeability test website(the most recent version of the footer) missing these three lines did not seem to make a difference.
> fixes filter scrolling bar

- website/static/website/css/base.css
- website/static/website/css/member.css
#727 
Fixes the mouse over image to not show a blank. Also on a individual person page it will no longer show a blank as well.
> Fixes the mouse over image to not show a blank

- website/static/website/css/base.css
- website/static/website/css/member.css
#728 
Removes added vertical space between name and image of person. It still maintains the added margin on the individual member page
Before:
After:
> Removes added vertical space between names and images

- website/static/website/css/base.css
- website/static/website/css/talks.css
#738 
If the functionality looks good, we may want to consider adjusting the padding/margin below each talk after merging.
> shows links beneath talks on hover

- website/static/website/css/base.css
- website/static/website/css/talks.css
#738 
address the concerns you had after the first merge of this issue. It now has shows the links beneath talks all the time in mobile view.
> Fixes talks in mobile view as well as hover on homepage

- website/static/website/js/publications.js
- website/templates/website/publications.html
#749 
It's not blue or underlined as shown in the before and after.
Before:
After:
> paper titles are hyperlinked on pubs page

- website/models.py
- website/templates/website/member.html
#756 
I found an additional error with members who selected Computer Science and Engineering. They're department abbreviation would just be "CS". This was caused from a wrongly structured 'if else' statement. I added a department abbreviation for HCDE so it can be any of the listed below when entered into Django department field:
1. HCDE
2. Human Centered Design and Engineering
3. Human Centered Design & Engineering
Lastly, the awkward space was removed from between title and the comma before department.
Before:
After:
Before: 
After:
> fixes department abbreviation for HCDE and CSE. Removes added space after member title

- requirements.txt
#637 
#510 
Updates django to 2.1.7
Updates django-image-cropping to 1.2.0 to fix the error occurring in the admin panel for Django versions 2.1+.
I'm not sure why Github is highlighting `django-sortedm2m-filter-horizontal-widget` in its compare code feature, but it should remain unaffected.
> Django Update 2.1.7: fixes Sever Error (500)

- website/templates/snippets/display_short_carousel_snippet.html
#685 
As discussed in the issue, we've decided to remove the article title from the carousel banner for each article. 
Before:
After:
> News title fix

- website/templates/website/people.html
#770 
reorganizes the people page so current member and collaborators and shown before past members
Before:
<hr />
After:
> reorganizes the people page

- website/static/website/css/project.css
- website/templates/website/project.html
#769 
I edited the css a bit and included a class that should have probably been included on the caption. It was not split screening the with "about" text because the caption had no maximum width.
Before:
After:
Before:
After:
Before:
After:
> fixes the visual project picture from not split with the about text

- website/static/website/css/autocomplete.css
- website/static/website/css/backtop.css
- website/static/website/css/base.css
- website/static/website/css/bignews.css
- website/static/website/css/carousel_fade.css
- website/static/website/css/faq.css
- website/static/website/css/fixed_side_bar.css
- website/static/website/css/grayscale.css
- website/static/website/css/index.css
- website/static/website/css/member.css
- website/static/website/css/news-listing.css
- website/static/website/css/news.css
- website/static/website/css/people.css
- website/static/website/css/project.css
- website/static/website/css/publications.css
- website/static/website/css/talks.css
#664 
I removed any unused CSS and did a quick clean up of the CSS style. 
I know I recommend using UnCSS in my report. However, I found that UnCSS had some issues parsing our html because of Django. I instead used another tool called PurifyCSS and that did the trick. I then ran the CSS through CSS Lint to fix some of the basic styling errors.
All the CSS files have been modified to 2 space indents. This is a very common practice for CSS and recommended by [Harry Roberts](https://cssguidelin.es/#the-importance-of-a-styleguide) (he's included in my report), 
"At a very high-level, we want
- two(2) space indents, no tabs;
- 80character wide columns;
- multi-line CSS;
- meaningful use of whitespace.
But, as with anything, the specifics are somewhat irrelevant—consistency is key."
The next …
> CSS Cleanup Part 1 and 2

- website/templates/snippets/display_project_gallery_lightbox.html
#692 
For some reason there is an error when finding the image sources on the test server even though the code worked on my local dev. I tried a slightly new line code to see if that will fix the issue. I'm going to merge right away so I can see if it's still broken.
> testing fix for missing images in lightbox test website

- website/views.py
#663 
Fixes the news listing banners by showing the assigned 'news listing' banners and not the front page banners
> News listing banners bug fix

- website/templates/snippets/display_short_carousel_snippet.html
- website/templates/website/base.html
- website/templates/website/news.html
Changes navbar on news page to white theme and removes banner
Before:
After:
> Changes navbar on news page to white theme and removes banner

- website/static/website/js/citationPopover.js
#785 
Adds DOI link at the end of citation format and changes 'url' to 'doi' in bibtex format
With DOI
> Adds DOI link in citations

- website/static/website/js/citationPopover.js
Adds a space before DOI and fixes an if statement I test that believe lead to a DOI link with no url
Before:
After:
> Fixes minor DOI link bugs for Citation popover

- website/templates/website/member.html
- website/templates/website/news-listing.html
- website/templates/website/news.html
- website/templates/website/project.html
- website/templatetags/ml_tags.py
#618 
Adds a custom django template tag that removes any html from a string. I placed this tag anywhere that has a 'news text preview'. So that affects member page 'recent news', project page 'recent news', news listing page, and news 'recent news'.
Before:
After:
> Fixes HTML formatted news listing text previews

- website/static/website/css/bignews.css
- website/static/website/css/news.css
- website/templates/website/news.html
#793
The left margin on news articles was not perfectly aligned.
After:
> Fixes left margin alignment on news article page

- website/models.py
Per request of @jonfroehlich, added "talk type" field to Talk model mentioned in Issue #531 
Changes made:
- As listed in #531, added a choice field for talk type 
Testing:
- To be merged into production
> Added New Field to Talks for Testing in Production

- website/models/publication.py
Fixes #1007 
Fixes a syntax error in the bibtex that we generate. We were missing a comma after the author field. I also removed the spaces around the `=` sign for consistency :)
Before
After
> Fixes bibtex syntax error

- docker-entrypoint.sh
- website/management/commands/generate_slugs_for_old_news_items.py
- website/models/news.py
- website/templates/snippets/display_news_blurb_sidebar_snippet.html
- website/templates/website/base.html
- website/templates/website/index.html
- website/templates/website/news-listing.html
- website/templates/website/news.html
- website/urls.py
- website/utils/ml_utils.py
- website/views/news.py
We can now visit news pages by their "slugs", which is a human-readable url from the title
So, rather than:
https://makeabilitylab-test.cs.washington.edu/news/58/
We can visit:
https://makeabilitylab-test.cs.washington.edu/news/professor-froehlich-receives-pactrans-outstanding-researcher-award/
> Update news to use slugs

- website/templates/snippets/display_pub_snippet.html
And they underline on mouseover. Addresses: https://github.com/makeabilitylab/makeabilitylabwebsite/issues/1134
> Adds href to pub titles
